// Mocks generated by Mockito 5.4.6 from annotations
// in neihborhoodwatch/test/features/incident/presentation/pages/incident_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:neihborhoodwatch/features/incident/domain/entities/incident.dart'
    as _i4;
import 'package:neihborhoodwatch/features/incident/domain/repositories/incident_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IncidentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncidentRepository extends _i1.Mock
    implements _i2.IncidentRepository {
  MockIncidentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Incident>> getAllIncidents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllIncidents, []),
            returnValue: _i3.Future<List<_i4.Incident>>.value(<_i4.Incident>[]),
          )
          as _i3.Future<List<_i4.Incident>>);

  @override
  _i3.Future<void> addIncident(_i4.Incident? incident) =>
      (super.noSuchMethod(
            Invocation.method(#addIncident, [incident]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateIncident(_i4.Incident? incident) =>
      (super.noSuchMethod(
            Invocation.method(#updateIncident, [incident]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteIncident(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIncident, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IncidentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncidentRepositoryTest extends _i1.Mock
    implements _i2.IncidentRepository {
  MockIncidentRepositoryTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Incident>> getAllIncidents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllIncidents, []),
            returnValue: _i3.Future<List<_i4.Incident>>.value(<_i4.Incident>[]),
          )
          as _i3.Future<List<_i4.Incident>>);

  @override
  _i3.Future<void> addIncident(_i4.Incident? incident) =>
      (super.noSuchMethod(
            Invocation.method(#addIncident, [incident]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateIncident(_i4.Incident? incident) =>
      (super.noSuchMethod(
            Invocation.method(#updateIncident, [incident]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteIncident(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIncident, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
